import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportToPDF = ({
  title = "Report",
  fileName = "Report",
  headers = [],
  rows = [],
  summary = null,
}) => {
  const doc = new jsPDF();

  // ==========================
  // Header
  // ==========================

  doc.setFontSize(20);
  doc.setTextColor(33, 37, 41);

  doc.text(
    "Medical Shop Management System",
    14,
    18
  );

  doc.setFontSize(14);

  doc.text(title, 14, 28);

  doc.setFontSize(10);

  doc.setTextColor(100);

  doc.text(
    `Generated On : ${new Date().toLocaleString()}`,
    14,
    36
  );

  // ==========================
  // Table
  // ==========================

  autoTable(doc, {
    startY: 45,

    head: [headers],

    body: rows,

    styles: {
      fontSize: 10,
      cellPadding: 3,
    },

    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      halign: "center",
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },

    theme: "grid",
  });

  // ==========================
  // Summary (Optional)
  // ==========================

  if (summary) {
    let y =
      doc.lastAutoTable.finalY + 12;

    doc.setFontSize(12);

    doc.setTextColor(0);

    Object.entries(summary).forEach(
      ([key, value], index) => {
        doc.text(
          `${key} : ${value}`,
          14,
          y + index * 8
        );
      }
    );
  }

  // ==========================
  // Footer
  // ==========================

  const pageHeight =
    doc.internal.pageSize.height;

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    "Generated by Medical Shop Management System",
    14,
    pageHeight - 10
  );

  doc.save(`${fileName}.pdf`);
};